### ISSUE TITLE
Merhaba Repoyu Fork Ettim Eline Sağlık

### ISSUE THREAD

**Issue by alicanyucel** [EfrunEvdi/CSharp-Baslangic-ve-Ileri-Duzey#1]
Linkendinden engellemem lazımdı, oradan engelledim github projelerini inceliyorum

**Comment by EfrunEvdi** [comment]
Çok teşekkür ederim :)

**Comment by alicanyucel** [comment]
Linkedlnden engellemem lazımdı github projelerini inceliyorum

**Comment by EfrunEvdi** [comment]
NE yapı8yosun analamadım ki ben seni ya ???
